image: docker:git
services:
  - docker:dind
variables:
  ENV_IMAGE: osrf/ros2:bouncy-ros-base
  BUILD_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
stages:
  - build

build:
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker run --name build-container -dit $ENV_IMAGE /bin/bash
    - docker exec build-container /bin/bash -c 'mkdir -p /ros2_ws/src'
    - docker exec build-container /bin/bash -c 'apt update && apt install -y python3-colcon-common-extensions python-rosdep && rosdep init && rosdep update'
    - docker cp $CI_PROJECT_DIR build-container:/ros2_ws/src/
    - docker exec -w /ros2_ws build-container /bin/bash -c 'source /opt/ros/bouncy/setup.bash && rosdep install --from-paths src --ignore-src --rosdistro bouncy -r -y'
    - docker exec -w /ros2_ws build-container /bin/bash -c 'source /opt/ros/bouncy/setup.bash && colcon build --symlink-install'
    - docker commit build-container $BUILD_IMAGE
    - docker push $BUILD_IMAGE