# Travis Continuous Integration Configuration File For ROS Control Projects
language: generic
services:
  - docker

notifications:
  email:
    recipients:
      - enrique.fernandez.perdomo@gmail.com
      - bence.magyar.robotics@gmail.com
      - gennaro.raiola@gmail.com
    on_success: change #[always|never|change] # default: change
    on_failure: change #[always|never|change] # default: always

env:
  matrix:
    - ROS_DISTRO=kinetic ROS_REPO=ros                UPSTREAM_WORKSPACE='https://raw.github.com/ros-controls/ros_control/\kinetic-devel/ros_control.rosinstall -control_msgs'
    - ROS_DISTRO=kinetic ROS_REPO=ros-testing        UPSTREAM_WORKSPACE='https://raw.github.com/ros-controls/ros_control/\kinetic-devel/ros_control.rosinstall -control_msgs'
    - ROS_DISTRO=melodic ROS_REPO=ros                UPSTREAM_WORKSPACE='https://raw.github.com/ros-controls/ros_control/\melodic-devel/ros_control.rosinstall -control_msgs'
    - ROS_DISTRO=melodic ROS_REPO=ros-testing        UPSTREAM_WORKSPACE='https://raw.github.com/ros-controls/ros_control/\melodic-devel/ros_control.rosinstall -control_msgs'
    - ROS_DISTRO=melodic ROS_REPO=ros BUILDER=colcon UPSTREAM_WORKSPACE='https://raw.github.com/ros-controls/ros_control/\melodic-devel/ros_control.rosinstall -control_msgs'

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
- .industrial_ci/travis.sh
