language: generic
services:
  - docker

env:
  matrix:
    - ROS_DISTRO="crystal" ROS_REPO=testing
    - ROS_DISTRO="crystal" ROS_REPO=main
    - ROS_DISTRO="dashing" ROS_REPO=testing
    - ROS_DISTRO="dashing" ROS_REPO=main

install:
  -  git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh
