# A list of MotionPrimitive messages that are executed in sequence. They don't have to be of the
# same type, as long as the robot supports executing them one after another.
MotionPrimitiveSequence trajectory
---
int32 SUCCESSFUL = 0
int32 INVALID_GOAL = -1
int32 OLD_HEADER_TIMESTAMP = -3

int32 error_code
string error_string
---
# Index of the currently executed motion primitive in the sequence.
uint8 current_primitive_index
