MotionPrimitiveSequence trajectory
---
int32 SUCCESSFUL = 0
int32 INVALID_GOAL = -1
int32 OLD_HEADER_TIMESTAMP = -3

int32 error_code
string error_string
---
uint8 current_primitive_index # How far are we in the actual trajectory?
