# This action interface is for commanding GPIOToolController to disengage or engage the tool.
# The tools are going through the predefed transitions in  during disengaging and engaging processes.
# Those are returned as feedback.

bool engage # boolean value to indicate if the tool should engaged (true) or disengaged (false). true for open, false for close)
---
bool success  # true for performing the tool command successfully and vice versa
string message #  informational, e.g. for success or error messages
---
GPIOToolTransition transition  # current transition of the gripper during enagagin/disengaging processes
