# This action interface is defined for controlling the io gripper controller to open or close the gripper

# The grippers are going through the different states during opening and closing process.
# Those are returned as feedback.

bool open # boolean value to indicate if the gripper should be opened or closed (e.g. true for open, false for close)
---
bool success # true for performing the gripper command successfully and vice versa
string message # informational, e.g. for success or error messages
---
IOGripperState transition # state of the gripper during transition as defined above
