# This action interface is defined for controlling the io gripper controller to open or close the gripper

# The grippers are going through the different states during opening and closing process.
# Those are returned as feedback.

# The gripper is in an idle state, not performing any action.
uint8 IDLE=0 
# The gripper is setting command interfaces to be able to perform open or close action, e.g., disabling breaks.
uint8 SET_BEFORE_COMMAND=1
# The close comand is sent to gripper on its command interfaces.
uint8 CLOSE_GRIPPER=2
# The controller is checking its current gripper's state on state interfaces.
uint8 CHECK_GRIPPER_STATE=3
# The open comand is sent to gripper on its command interfaces.
uint8 OPEN_GRIPPER=4
# The gripper is setting "after" commands when open or close process if finished, e.g., engaging breaks.
uint8 SET_AFTER_COMMAND=5
# The gripper has halted due to an error or stop command.
uint8 HALTED=6

bool open # boolean value to indicate if the gripper should be opened or closed (e.g. true for open, false for close)
---
bool success # true for performing the gripper command successfully and vice versa
string message # informational, e.g. for success or error messages
---
uint8 state # state of the gripper as defined above
