# This action interface is defined for setting the configuration of the io gripper controller
# In yaml file of the io_gripper_controller, the configuration is defined as a list of strings
# e.g. configurations: ["narrow_objects", "wide_objects"]
# The action request is called with the name of the configuration to be set

# The io_gripper_controller follows a set of states to reconfigure the gripper

string config_name # information about which configuration is being set for the gripper controller
---
bool result # indicate success for setting the configuration of the gripper controller and vice versa
string status # informational, e.g. for success or error messages
---
IOGripperState transition # state of the gripper during transition as defined above
