# This action interface is defined for setting the configuration of the GPIOToolController.
# In yaml file of the controller, the configurations are defined as a list of strings, for example a gripper might have the following configurations: ["narrow_objects", "wide_objects"], or a lift unit on a mobile base might have configurations like ["with_payload", "without_payload"].
# The action request is called with the name of the configuration to be set.
# During the configuration change, the gripper is going through a set of transitions, which are defined in the GPIOToolTransition message.

string config_name # information about which configuration is being set for tool
---
bool success  # indicate success for setting the configuration of the tool and vice versa
string message  # informational, e.g. for success or error messages
