name: Pre-Commit

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  pre-commit-iron:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-pre-commit.yml@master
    with:
      ros_distro: iron
      os_name: ubuntu-22.04

  pre-commit-rolling:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-pre-commit.yml@master
    with:
      ros_distro: rolling
      container: ubuntu:24.04
