name: Humble Pre-Commit

on:
  workflow_dispatch:
  pull_request:
    branches:
      - humble

jobs:
  pre-commit:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-pre-commit.yml@master
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [humble]
    with:
      ros_distro: ${{ matrix.ROS_DISTRO }}
      os_name: ubuntu-22.04
