name: Jazzy Binary Build
# author: Denis Štogl <denis@stoglrobotics.de>
# description: Build & test all dependencies from released (binary) packages.

on:
  workflow_dispatch:
  pull_request: &event
    branches:
      - jazzy
    paths:
      - '**.action'
      - '**.msg'
      - '**.srv'
      - '.github/workflows/jazzy-build.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
  push: *event
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '28 6 * * MON-FRI'

concurrency:
  # cancel previous runs of the same workflow, except for pushes on given branches
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/heads') }}

jobs:
  binary:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@master
    strategy:
      fail-fast: false
      matrix:
        ROS_REPO: [main, testing]
    with:
      ros_distro: jazzy
      ros_repo: ${{ matrix.ROS_REPO }}
      ref_for_scheduled_build: jazzy
